In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Preprocessing 1: Cleaning Data and Sampling

In [ ]:
df=pd.read_csv("IAKR2015-16.csv")
df = df.sample(frac=0.10, random_state=1)#Using only 10% data to reduce computation power. Simple random sampling used here

C:\Users\1liki\AppData\Local\Temp\ipykernel_5184\2037002617.py:1: DtypeWarning: Columns (36,46,86,114,282,289,291,303,305,326,409,410,411,413,414,415,416,417,418,425,503,504,510,560,561,562,566,656,657,661,665,669,673,677,681,685,689,694,742,743,774,778,807,813,814,917,926,962,963,964,966,968,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1221,1222,1223,1230,1231,1307,1311,1315,1319,1324,1325,1332,1336) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("IAKR2015-16.csv")

In [ ]:
df

,CASEID,MIDX,V000,V001,V002,V003,V004,V005,V006,V007,...,S560,S561,S562,S563A,S563B,S563C,S564,S565A,S565B,S565C
162254,26035424 02,1,IA6,260354,24,2,354,184616,2,2016,...,0,,0,,,,1,1,1,1
225350,33317649 02,1,IA6,333176,49,2,3176,743042,5,2016,...,,,0,,,,0,,,
193094,29163815 02,1,IA6,291638,15,2,1638,904324,3,2016,...,,,0,,,,0,,,
164202,26062418 03,1,IA6,260624,18,3,624,618850,3,2016,...,1,1,1,1,1,0,1,1,1,1
124847,19207101 02,1,IA6,192071,1,2,2071,761600,4,2015,...,,,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48608,07048405 07,2,IA6,70484,5,7,484,294546,3,2016,...,1,1,1,1,1,1,1,1,1,1
90623,15099274 02,1,IA6,150992,74,2,992,603823,4,2016,...,,,0,,,,0,,,
108029,19033295 02,1,IA6,190332,95,2,332,1054690,3,2015,...,3,1,1,1,0,1,1,1,0,1
84726,15033106 02,1,IA6,150331,6,2,331,805916,9,2016,...,,,0,,,,0,,,
7977,03070904 02,1,IA6,30709,4,2,709,29875,5,2016,...,,,1,1,0,0,0,,,

In [ ]:
df.head()

,CASEID,MIDX,V000,V001,V002,V003,V004,V005,V006,V007,...,S560,S561,S562,S563A,S563B,S563C,S564,S565A,S565B,S565C
162254,26035424 02,1,IA6,260354,24,2,354,184616,2,2016,...,0,,0,,,,1,1,1,1
225350,33317649 02,1,IA6,333176,49,2,3176,743042,5,2016,...,,,0,,,,0,,,
193094,29163815 02,1,IA6,291638,15,2,1638,904324,3,2016,...,,,0,,,,0,,,
164202,26062418 03,1,IA6,260624,18,3,624,618850,3,2016,...,1,1,1,1,1,0,1,1,1,1
124847,19207101 02,1,IA6,192071,1,2,2071,761600,4,2015,...,,,1,1,1,1,1,1,1,1

In [ ]:
df = df.replace(['NO DATA','N/A', ' ', ''," 01000110    02", " 33143713    02", " 11083558    02", " 14002920    02", " 26035424    02"],np.nan)

In [ ]:
df.isna().any().tolist()

[True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 ...]

In [ ]:
df = df.fillna(df.median())

C:\Users\1liki\AppData\Local\Temp\ipykernel_5184\3493596106.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df = df.fillna(df.median())

In [ ]:
df.isna().any().tolist()

[True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 ...]

In [ ]:
df=df.dropna(axis=1)

In [ ]:
check_nan = df.isnull().values.any()
 
# printing the result
print(check_nan)

False

In [ ]:
df

,MIDX,V000,V001,V002,V003,V004,V005,V006,V007,V008,...,S560,S561,S562,S563A,S563B,S563C,S564,S565A,S565B,S565C
162254,1,IA6,260354,24,2,354,184616,2,2016,1394,...,0,1.0,0,1.0,1.0,1.0,1,1,1,1
225350,1,IA6,333176,49,2,3176,743042,5,2016,1397,...,1.0,1.0,0,1.0,1.0,1.0,0,1.0,1.0,1.0
193094,1,IA6,291638,15,2,1638,904324,3,2016,1395,...,1.0,1.0,0,1.0,1.0,1.0,0,1.0,1.0,1.0
164202,1,IA6,260624,18,3,624,618850,3,2016,1395,...,1,1,1,1,1,0,1,1,1,1
124847,1,IA6,192071,1,2,2071,761600,4,2015,1384,...,1.0,1.0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48608,2,IA6,70484,5,7,484,294546,3,2016,1395,...,1,1,1,1,1,1,1,1,1,1
90623,1,IA6,150992,74,2,992,603823,4,2016,1396,...,1.0,1.0,0,1.0,1.0,1.0,0,1.0,1.0,1.0
108029,1,IA6,190332,95,2,332,1054690,3,2015,1383,...,3,1,1,1,0,1,1,1,0,1
84726,1,IA6,150331,6,2,331,805916,9,2016,1401,...,1.0,1.0,0,1.0,1.0,1.0,0,1.0,1.0,1.0
7977,1,IA6,30709,4,2,709,29875,5,2016,1397,...,1.0,1.0,1,1,0,0,0,1.0,1.0,1.0

# Preprocessing 2: Creation of the Explained Variable "Immunization Score"

In [ ]:
df2= df.loc[:,["H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H0", "HEP0", "HEP1", "HEP2", "HEP3"]]

In [ ]:
df=df.drop(["H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H0", "HEP0", "HEP1", "HEP2", "HEP3", "H2D", "H3D", "H4D", "H5D", "H6D", "H7D", "H8D", "H9D", "H0D", "HEP0D", "HEP1D", "HEP2D", "HEP3D", "H2M", "H3M", "H4M", "H5M", "H6M", "H7M", "H8M", "H9M", "H0M", "HEP0M", "HEP1M", "HEP2M", "HEP3M", "H2Y", "H3Y", "H4Y", "H5Y", "H6Y", "H7Y", "H8Y", "H9Y", "H0Y", "HEP0Y", "HEP1Y", "HEP2Y", "HEP3Y", "V000"],axis=1)

In [ ]:
df

,MIDX,V001,V002,V003,V004,V005,V006,V007,V008,V009,...,S560,S561,S562,S563A,S563B,S563C,S564,S565A,S565B,S565C
162254,1,260354,24,2,354,184616,2,2016,1394,5,...,0,1.0,0,1.0,1.0,1.0,1,1,1,1
225350,1,333176,49,2,3176,743042,5,2016,1397,10,...,1.0,1.0,0,1.0,1.0,1.0,0,1.0,1.0,1.0
193094,1,291638,15,2,1638,904324,3,2016,1395,8,...,1.0,1.0,0,1.0,1.0,1.0,0,1.0,1.0,1.0
164202,1,260624,18,3,624,618850,3,2016,1395,4,...,1,1,1,1,1,0,1,1,1,1
124847,1,192071,1,2,2071,761600,4,2015,1384,5,...,1.0,1.0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48608,2,70484,5,7,484,294546,3,2016,1395,6,...,1,1,1,1,1,1,1,1,1,1
90623,1,150992,74,2,992,603823,4,2016,1396,12,...,1.0,1.0,0,1.0,1.0,1.0,0,1.0,1.0,1.0
108029,1,190332,95,2,332,1054690,3,2015,1383,6,...,3,1,1,1,0,1,1,1,0,1
84726,1,150331,6,2,331,805916,9,2016,1401,3,...,1.0,1.0,0,1.0,1.0,1.0,0,1.0,1.0,1.0
7977,1,30709,4,2,709,29875,5,2016,1397,1,...,1.0,1.0,1,1,0,0,0,1.0,1.0,1.0

In [ ]:
df2

       H2 H3 H4 H5 H6 H7 H8 H9 H0 HEP0 HEP1 HEP2 HEP3
162254  2  2  2  2  2  2  2  2  2    0    2    2    2
225350  1  1  1  1  1  1  1  1  0    0    1    1    1
193094  2  1  1  1  1  1  1  1  2    2    1    1    1
164202  2  2  2  2  2  2  0  2  2    2    2    2    0
124847  2  2  2  2  2  2  0  2  2    2    2    2    0
...    .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...
48608   1  1  3  1  3  1  3  1  1    1    1    1    1
90623   1  3  1  3  1  1  3  0  1    3    3    3    3
108029  1  1  1  1  1  1  1  1  0    0    1    1    3
84726   2  2  2  2  2  2  2  2  2    2    2    2    2
7977    2  2  2  2  2  0  0  8  0    0    2    2    0

[25963 rows x 13 columns]

In [ ]:
df2=df2.astype(int)

In [ ]:
df2 = df2.replace([1,2,3],value=1)

In [ ]:
df2 = df2.replace([0,8,9],value=0)

In [ ]:
df2.head()

        H2  H3  H4  H5  H6  H7  H8  H9  H0  HEP0  HEP1  HEP2  HEP3
162254   1   1   1   1   1   1   1   1   1     0     1     1     1
225350   1   1   1   1   1   1   1   1   0     0     1     1     1
193094   1   1   1   1   1   1   1   1   1     1     1     1     1
164202   1   1   1   1   1   1   0   1   1     1     1     1     0
124847   1   1   1   1   1   1   0   1   1     1     1     1     0

In [ ]:
df2

        H2  H3  H4  H5  H6  H7  H8  H9  H0  HEP0  HEP1  HEP2  HEP3
162254   1   1   1   1   1   1   1   1   1     0     1     1     1
225350   1   1   1   1   1   1   1   1   0     0     1     1     1
193094   1   1   1   1   1   1   1   1   1     1     1     1     1
164202   1   1   1   1   1   1   0   1   1     1     1     1     0
124847   1   1   1   1   1   1   0   1   1     1     1     1     0
...     ..  ..  ..  ..  ..  ..  ..  ..  ..   ...   ...   ...   ...
48608    1   1   1   1   1   1   1   1   1     1     1     1     1
90623    1   1   1   1   1   1   1   0   1     1     1     1     1
108029   1   1   1   1   1   1   1   1   0     0     1     1     1
84726    1   1   1   1   1   1   1   1   1     1     1     1     1
7977     1   1   1   1   1   0   0   0   0     0     1     1     0

[25963 rows x 13 columns]

In [ ]:
df2=df2.astype(int)

In [ ]:
check_nan = df2.isnull().values.any()
 
# printing the result
print(check_nan)

False

In [ ]:
totals=df2.sum()

In [ ]:
print(totals)

H2      23066
H3      21875
H4      22219
H5      20435
H6      20568
H7      18312
H8      17016
H9      17953
H0      18845
HEP0    15430
HEP1    19225
HEP2    17701
HEP3    13816
dtype: int64

In [ ]:
# The 5 maximum weights are:
# H2,H3,H4,H5,H6

In [ ]:
weights=totals[["H2","H3","H4","H5","H6"]]
weights

H2    23066
H3    21875
H4    22219
H5    20435
H6    20568
dtype: int64

In [ ]:
index=weights.index
values=weights.values

In [ ]:
index[0]

'H2'

In [ ]:
Y=df2[index[0]]*values[0]+df2[index[1]]*values[1]+df2[index[2]]*values[2]+df2[index[3]]*values[3]+df2[index[4]]*values[4]

In [ ]:
Y=Y/(weights.sum())

In [ ]:
Y

162254    1.0
225350    1.0
193094    1.0
164202    1.0
124847    1.0
         ...
48608     1.0
90623     1.0
108029    1.0
84726     1.0
7977      1.0
Length: 25963, dtype: float64

In [ ]:
#The Y we generated here is the immunization score formed by using the most common vaacinations as inputs

# Preprocessing 3: Feature Subset Selection

In [ ]:
print(df.dtypes)

MIDX      int64
V001      int64
V002      int64
V003      int64
V004      int64
          ...
S563C    object
S564     object
S565A    object
S565B    object
S565C    object
Length: 1048, dtype: object

In [ ]:
import pandas as pd
import numpy as np

def select_k_best(X, y, k=10):
    """
    Selects the k best features from X using mutual information regression.
    """
    # Convert string values to numerical values
    for i, x_i in enumerate(X.T):
        if isinstance(x_i[0], str):
            unique_vals = np.unique(x_i)
            encoding_dict = dict(zip(unique_vals, range(len(unique_vals))))
            X[:, i] = np.vectorize(encoding_dict.get)(x_i)

    # Calculate mutual information scores
    mi_scores = np.zeros(X.shape[1])
    for i in range(X.shape[1]):
        mi_scores[i] = calc_mi(X[:, i], y)

    # Select the top k features
    top_k_idx = mi_scores.argsort()[::-1][:k]
    return X[:, top_k_idx], top_k_idx

def calc_mi(x, y):
    """
    Calculates the mutual information between x and y using the formula:
    MI(x,y) = sum( p(x,y) * log2( p(x,y) / (p(x) * p(y)) ) )
    """
    # Convert to integer values
    x_int = np.asarray(x, dtype=int)
    y_int = np.asarray(y, dtype=int)

    # Calculate the joint probability distribution
    joint_prob = np.zeros((np.unique(x_int).shape[0], np.unique(y_int).shape[0]))
    for i in range(x_int.shape[0]):
        joint_prob[x_int[i], y_int[i]] += 1
    joint_prob /= x_int.shape[0]

    # Calculate the marginal probability distributions
    x_prob = np.sum(joint_prob, axis=1)
    y_prob = np.sum(joint_prob, axis=0)

    # Calculate the mutual information
    mi = 0
    for i in range(joint_prob.shape[0]):
        for j in range(joint_prob.shape[1]):
            if joint_prob[i,j] > 0:
                mi += joint_prob[i,j] * np.log2(joint_prob[i,j] / (x_prob[i] * y_prob[j]))

    return mi

X = df
X_train_new, selected_feature_idx = select_k_best(X.astype(str).values, Y.values, k=10)
new_features = X.columns[selected_feature_idx]
print(new_features)

Index(['V191', 'S191R', 'V001', 'V021', 'V005', 'SV005', 'V444', 'HW10', 'HW4',
       'V443'],
      dtype='object')

In [ ]:
df = df[new_features]

In [ ]:
df

,V191,S191R,V001,V021,V005,SV005,V444,HW10,HW4,V443
162254,78464,-24506.0,260354,260354,184616,249333,11602,256,945,10641
225350,-9747,25044,333176,333176,743042,689906,12605,284,9999,10685
193094,-52391,-23369,291638,291638,904324,1037949,8990,413,28,8009
164202,35428,76331,260624,260624,618850,835789,10161,2101,4699,8751
124847,116646,168537,192071,192071,761600,1092650,13258,65,442,11027
...,...,...,...,...,...,...,...,...,...,...
48608,68058,113375,70484,70484,294546,448920,10947,402,972,9105
90623,-107192,-85583,150992,150992,603823,995776,8114,7982,3402,6676
108029,32741,73280,190332,190332,1054690,1513140,10702,1017,765,9643
84726,152870,-24506.0,150331,150331,805916,1329052,11384,6217,3,8659
7977,414,36580,30709,30709,29875,707165,13237,2,8555,11477